"""add avatar_url to users, sync with development merge

Revision ID: 5a962917b02b
Revises: 7a3745187411
Create Date: 2026-09-06 15:33:02.827589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a962917b02b'
down_revision = '7a3745187411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_reference', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('pesapal_tracking_id', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint('uq_orders_merchant_reference', ['merchant_reference'])
        batch_op.create_unique_constraint('uq_orders_pesapal_tracking_id', ['pesapal_tracking_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_pesapal_tracking_id', type_='unique')
        batch_op.drop_constraint('uq_orders_merchant_reference', type_='unique')
        batch_op.drop_column('pesapal_tracking_id')
        batch_op.drop_column('merchant_reference')

    # ### end Alembic commands ###
