"""initial migration with mpesa checkout request id

Revision ID: 7a3745187411
Revises: 
Create Date: 2026-09-03 23:16:16.399652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3745187411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('cover_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=400),
               existing_nullable=True)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('stock_for_lending',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_new_arrival',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_popular',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_books_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_genre'), ['genre'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_title'), ['title'], unique=False)

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_checkout_request_id', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_mpesa_checkout_request_id'), ['mpesa_checkout_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_mpesa_checkout_request_id'))
        batch_op.drop_column('mpesa_checkout_request_id')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_title'))
        batch_op.drop_index(batch_op.f('ix_books_genre'))
        batch_op.drop_index(batch_op.f('ix_books_author'))
        batch_op.alter_column('is_popular',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_new_arrival',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('stock_for_lending',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('cover_url',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
